#!/bin/bash
PUERTO_SERIAL="/dev/rotor"
MODELO="201"
BAUDRATE="9600"


case "$1" in

start)
    echo -n "Iniciando demonio de control del rotor                    "
    rotctld -m $MODELO -r $PUERTO_SERIAL -s $BAUDRATE &
    if [ $? -eq 0 ]; then
        echo  -e "\e[01;34mLISTO\e[00m"
    else
        echo  -e "\e[01;31mERROR\e[00m"
        exit 1
    fi
;;
stop)

    echo -n "Deteniendo demonio de control del rotor                   "
    killall -9 rotctld 2>/dev/null >/dev/null
        if [ $? -eq 0 ]; then
                echo -e "\e[01;34mLISTO\e[00m"
        else
                echo -e "\e[01;31mERROR\e[00m"
        exit 1
        fi
;;
status)
        if [ -n "$(ps -A|grep rotctld| cut -d ' ' -f 2)" ]; then
                echo -e "\e[01;34mControl del rotor corriendo =)\e[00m"
        else
                echo -e "\e[01;31mControl del rotor abajo\e[00m"

        fi
;;
restart)
    echo -n "Reiniciando demonio de control de la radio                "
    killall -9 rotctld 2>/dev/null >/dev/null  && rotctld -m $MODELO -r $PUERTO_SERIAL -s $BAUDRATE & 2>/dev/null >/dev/null
        if [ $? -eq 0 ]; then
                echo  -e "\e[01;34mLISTO\e[00m"
        else
                echo -e "\e[01;31mERROR\e[00m"
        exit 1
        fi
;;
*)
    echo "Uso: controlrotor {start|stop|restart}"
    exit 1
esac